### ISSUE TITLE
Create_models

### ISSUE THREAD

**Issue by sapient369** [eSkortz/fl_aiogram_cryptochannel#2]
Sorry bother you again( @eSkortz
When i am runing Create models
I am getting error tried different ways changed code but still couldnt fix. Can you help please?!

Traceback (most recent call last):
File "/root/test/utils/create_models.py", line 6, in
from config.config_reader import database_config
ModuleNotFoundError: No module named 'config'

**Comment by eSkortz** [comment]
change 'import config.config_reader' to 'config_reader'
